'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const express=require('express');
const path=require('path');
process.env.LOGIN_JWT_SECRET='enms-test-secret-at-least-thirty-two-characters';
const {createLoginToken}=require('../services/login-jwt');
const {createStore}=require('../public/enms/mock');
const {api,pages,menu}=require('../routes/enms');
async function withServer(fn){const app=express();app.use(express.json());app.set('views',path.join(__dirname,'../views'));app.set('view engine','ejs');app.use('/api/enms/v1',api);app.use('/enms',pages);const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{await fn('http://127.0.0.1:'+server.address().port);}finally{await new Promise(r=>server.close(r));}}
const token=id=>createLoginToken({mataikhoan:id,taikhoan:'tester'});
const headers=id=>({'Content-Type':'application/json',Authorization:'Bearer '+token(id)});
test('EnMS mock has 16 stations, 71 unique meters and consistent station counts',()=>{const store=createStore();const stations=store.request('GET','stations'),meters=store.request('GET','meters');assert.equal(stations.length,16);assert.equal(meters.length,71);assert.equal(new Set(meters.map(m=>m.id)).size,71);for(const s of stations)assert.equal(meters.filter(m=>m.stationId===s.id).length,s.meters);assert.equal(meters.filter(m=>m.status==='Lỗi').length,2);const alerts=store.request('GET','alerts',{pageSize:100}).items;assert.deepEqual(['critical','warning','minor','info'].map(level=>alerts.filter(a=>a.severity===level).length),[3,7,5,12]);});
test('EnMS APIs reject missing, tampered and expired JWTs',async()=>withServer(async base=>{for(const authorization of ['', 'Bearer invalid','Bearer '+token(1)+'tampered']){const response=await fetch(base+'/api/enms/v1/summary',{headers:{authorization}});assert.equal(response.status,401);}const old=process.env.LOGIN_JWT_TTL;process.env.LOGIN_JWT_TTL='-1';const expired=token(1);if(old===undefined)delete process.env.LOGIN_JWT_TTL;else process.env.LOGIN_JWT_TTL=old;assert.equal((await fetch(base+'/api/enms/v1/summary',{headers:{Authorization:'Bearer '+expired}})).status,401);}));
test('EnMS authenticated API filters and paginates events; updates are isolated per user',async()=>withServer(async base=>{let response=await fetch(base+'/api/enms/v1/alerts?severity=critical&pageSize=2',{headers:headers(801)});let result=await response.json();assert.equal(response.status,200);assert.equal(result.data.total,3);assert.equal(result.data.items.length,2);assert.equal(result.meta.source,'mock');const update={status:'Đã xác nhận',assignee:'Phòng kỹ thuật',note:'Đã kiểm tra tại trạm'};response=await fetch(base+'/api/enms/v1/alerts/1',{method:'PATCH',headers:headers(801),body:JSON.stringify(update)});assert.equal(response.status,200);result=await (await fetch(base+'/api/enms/v1/alerts/1',{headers:headers(801)})).json();assert.equal(result.data.note,update.note);result=await (await fetch(base+'/api/enms/v1/alerts/1',{headers:headers(802)})).json();assert.equal(result.data.note,'');response=await fetch(base+'/api/enms/v1/alerts/1',{method:'PATCH',headers:headers(801),body:JSON.stringify({...update,status:'invalid'})});assert.equal(response.status,400);}));
test('EnMS readings validate device, date order, interval and pagination',async()=>withServer(async base=>{for(const q of ['meterId=unknown','from=2025-06-12&to=2025-06-01','interval=0','page=-1','pageSize=1001','from=invalid']){const r=await fetch(base+'/api/enms/v1/readings?'+q,{headers:headers(1)});assert.ok([400,404].includes(r.status),q);}const r=await fetch(base+'/api/enms/v1/readings?meterId=MT-008&from=2025-06-01&to=2025-06-02&interval=60&page=2&pageSize=10',{headers:headers(1)});const result=await r.json();assert.equal(result.data.total,48);assert.equal(result.data.items.length,10);assert.ok(result.data.items.every(r=>r.meterId==='MT-008'));}));
test('EnMS reports are created and read back using authenticated endpoints',async()=>withServer(async base=>{const r=await fetch(base+'/api/enms/v1/reports',{method:'POST',headers:headers(901),body:JSON.stringify({type:'EnPI',from:'2025-06-01',to:'2025-06-10'})});assert.equal(r.status,201);const created=(await r.json()).data;const read=await fetch(base+'/api/enms/v1/reports/'+created.id,{headers:headers(901)});assert.equal((await read.json()).data.type,'EnPI');}));
test('All seven EnMS screens and settings render with the correct active menu; unknown pages return 404',async()=>withServer(async base=>{assert.equal(menu.length,8);assert.equal(menu.filter(item=>item.demo).length,7);for(const item of menu){const r=await fetch(base+'/enms/preview/'+item.id);assert.equal(r.status,200);const html=await r.text();assert.ok(html.includes('data-preview="true"'));assert.ok(html.includes('data-page="'+item.id+'"'));assert.equal((html.match(/aria-current="page"/g)||[]).length,1);}assert.equal((await fetch(base+'/enms/preview/missing')).status,404);}));
test('Live source fails closed instead of exposing mock as real data',async()=>withServer(async base=>{process.env.ENMS_DATA_SOURCE='database';try{const response=await fetch(base+'/api/enms/v1/summary',{headers:headers(1)});assert.equal(response.status,503);}finally{delete process.env.ENMS_DATA_SOURCE;}}));
