const express = require('express');
const router = new express.Router();
const ds_danhmuc = require('../controllers/ds_danhmuc.js');
const quanly_ds_taikhoan = require('../controllers/quanly_ds_taikhoan.js');
const quanly_ds_tk_by_danhmucid = require('../controllers/quanly_ds_tk_by_danhmucid.js');
const quanly_them_taikhoan = require('../controllers/quanly_them_taikhoan.js');
const quanly_sua_taikhoan = require('../controllers/quanly_sua_taikhoan.js');
const ds_thietbi_quanly_ioa = require('../controllers/ds_thietbi_quanly_ioa.js');
const quanly_ds_danhmuc = require('../controllers/quanly_ds_danhmuc.js');
const quanly_ds_khachhang = require('../controllers/quanly_ds_khachhang.js');
const quanly_ds_chungloaicongto = require('../controllers/quanly_ds_chungloaicongto.js');
const quanly_themdanhmuc = require('../controllers/quanly_themdanhmuc.js');
const quanly_them_diemdo = require('../controllers/quanly_them_diemdo.js');
const quanly_sua_tt_diemdo = require('../controllers/quanly_sua_tt_diemdo.js');
const quanly_sua_tt_cto = require('../controllers/quanly_sua_tt_cto.js');
const quanly_thay_imei = require('../controllers/quanly_thay_imei.js');
const quanly_suadanhmuc = require('../controllers/quanly_suadanhmuc.js');
const quanly_xoadanhmuc = require('../controllers/quanly_xoadanhmuc.js');
const quanly_ds_diemdo = require('../controllers/quanly_ds_diemdo.js');
const quanly_lay_tt_diemdo = require('../controllers/quanly_lay_tt_diemdo.js');
const quanly_ds_congto_byimei = require('../controllers/quanly_ds_congto_byimei.js');
const quanly_diemdo_thay_cto = require('../controllers/quanly_diemdo_thay_cto.js');
const quanly_thanhly_diemdo = require('../controllers/quanly_thanhly_diemdo.js');
const khaithacdulieu_laychisocongto = require('../controllers/khaithacdulieu_laychisocongto.js');
const khaithacdulieu_laythongsovanhanh = require('../controllers/khaithacdulieu_laythongsovanhanh.js');
const khaithacdulieu_laybieudophutai = require('../controllers/khaithacdulieu_laybieudophutai.js');
const khaithacdulieu_laychiso_pmax = require('../controllers/khaithacdulieu_laychiso_pmax.js');
const khaithacdulieu_laydulieusonghai = require('../controllers/khaithacdulieu_laydulieusonghai.js');
const khaithacdulieu_laychisocongto_dscongto = require('../controllers/khaithacdulieu_laychisocongto_dscongto.js');
const khaithacdulieu_laychisocongto_chitiet = require('../controllers/khaithacdulieu_laychisocongto_chitiet.js');
const khaithacdulieu_laythongsovanhanh_chitiet = require('../controllers/khaithacdulieu_laythongsovanhanh_chitiet.js');
const khaithacdulieu_sukiencongto_layloaicanhbao = require('../controllers/khaithacdulieu_sukiencongto_layloaicanhbao.js');
const khaithacdulieu_sukiencongto_laysukienct = require('../controllers/khaithacdulieu_sukiencongto_laysukienct.js');
const khaithacdulieu_laybieudophutai_chitiet = require('../controllers/khaithacdulieu_laybieudophutai_chitiet.js');
const khaithacdulieu_laychisopmax_chitiet = require('../controllers/khaithacdulieu_laychisopmax_chitiet.js');
const khaithacdulieu_dieukhiendongcat_laykh = require('../controllers/khaithacdulieu_dieukhiendongcat_laykh.js');
const khaithacdulieu_dieukhiendongcat_tcp = require('../controllers/khaithacdulieu_dieukhiendongcat_tcp.js');
const baocaohoatdong_getcambien = require('../controllers/baocaohoatdong_getcambien.js');
const baocaohoatdong = require('../controllers/baocaohoatdong.js');
const khaithacdulieu_dieukhiendongcat_insert_lichsu_dongcat = require('../controllers/khaithacdulieu_dieukhiendongcat_insert_lichsu_dongcat.js');
const ds_ioa_idcambien_IEC_104 = require('../controllers/ds_ioa_idcambien_IEC_104.js');
const ds_thietbi_cambien_IEC_104 = require('../controllers/ds_thietbi_cambien_IEC_104.js');
const sua_thietbi_IEC_104 = require('../controllers/sua_thietbi_IEC_104.js');
const sua_cambien_IEC_104 = require('../controllers/sua_cambien_IEC_104.js');
const sua_IOA_IEC_104 = require('../controllers/sua_IOA_IEC_104.js');
const xoa_thietbi_IEC_104 = require('../controllers/xoa_thietbi_IEC_104.js');
const xoa_cambien_IEC_104 = require('../controllers/xoa_cambien_IEC_104.js');
const xoa_IOA_IEC_104 = require('../controllers/xoa_IOA_IEC_104.js');
const khaibaotb_IEC_104 = require('../controllers/khaibaotb_IEC_104.js');
const khaibao_cambien_IEC_104 = require('../controllers/khaibao_cambien_IEC_104.js');
const khaibao_IOA_IEC_104 = require('../controllers/khaibao_IOA_IEC_104.js');
const ds_thietbi_IEC_104 = require('../controllers/ds_thietbi_IEC_104.js');
const ds_quanly_ioa_capnhatloai = require('../controllers/ds_thietbi_IEC_104.js');
const scada_thongsovanhanh = require('../controllers/scada_thongsovanhanh.js');
const scada_thongsovanhanh_getAll = require('../controllers/scada_thongsovanhanh_getAll.js');
const scada_ai_lotong = require('../controllers/scada_ai_lotong.js');
const scada_canhbao_ds_canhbao = require('../controllers/scada_canhbao_ds_canhbao.js');
const khaithacdulieu_sukiencongto_laysukien_tucthoi = require('../controllers/khaithacdulieu_sukiencongto_laysukien_tucthoi.js');
const canhbao_ds_laycanhbaovh = require('../controllers/canhbao_ds_laycanhbaovh.js');
const canhbao_ds_canhbaovanhanh = require('../controllers/canhbao_ds_canhbaovanhanh.js');
const canhbao_cauhinh_save_canhbao = require('../controllers/canhbao_cauhinh_save_canhbao.js');
const cauhinh_canhbao_IEC_104 = require('../controllers/cauhinh_canhbao_IEC_104.js');
const canhbao_cauhinh_save_canhbaovanhanh = require('../controllers/canhbao_cauhinh_save_canhbaovanhanh.js');
const canhbao_laydanhsach_vanhanh = require('../controllers/canhbao_laydanhsach_vanhanh.js');
const canhbao_get_udm = require('../controllers/canhbao_get_udm.js');
const canhbao_save_udm = require('../controllers/canhbao_save_udm.js');
const canhbao_apdung_udm = require('../controllers/canhbao_apdung_udm.js');
const canhbao_get_idm = require('../controllers/canhbao_get_idm.js');
const canhbao_save_idm = require('../controllers/canhbao_save_idm.js');
const canhbao_apdung_idm = require('../controllers/canhbao_apdung_idm.js');

const khaibaokhachhang_uploadfile = require('../controllers/khaibaokhachhang_uploadfile.js');
const thuydien_insertdata = require('../controllers/thuydien_insertdata.js');
const khaibaokhachhang_kiemtra = require('../controllers/khaibaokhachhang_kiemtra.js');
const khaibaokhachhang_thuchien = require('../controllers/khaibaokhachhang_thuchien.js');

const phanquyen_checkquyen = require('../controllers/phanquyen_checkquyen.js');
const phanquyen_ganquyen = require('../controllers/phanquyen_ganquyen.js');
const phanquyen_layds = require('../controllers/phanquyen_layds.js');
const login = require('../controllers/login.js');
const quanly_ds_danhmuc_getthietbi = require('../controllers/quanly_ds_danhmuc_getthietbi.js');
const quanly_ds_danhmuc_themthietbi = require('../controllers/quanly_ds_danhmuc_themthietbi.js');
const quanly_ds_danhmuc_suathietbi = require('../controllers/quanly_ds_danhmuc_suathietbi.js');
const quanly_xoadanhmuc_thietbi = require('../controllers/quanly_xoadanhmuc_thietbi.js');
const quanly_ds_danhmuc_user = require('../controllers/quanly_ds_danhmuc_user.js');
const baocaoloduongday = require('../controllers/baocaoloduongday.js');
const thietbitruyenthong_getkhachhang = require('../controllers/thietbitruyenthong_getkhachhang.js');
const thietbitruyenthong_cauhinhdieukhien = require('../controllers/thietbitruyenthong_cauhinhdieukhien.js');
const thietbitruyenthong_guilenhdoccauhinh = require('../controllers/thietbitruyenthong_guilenhdoccauhinh.js');
const baocaothongkemangtai = require('../controllers/baocaothongkemangtai.js');
const uoctinhtonthat = require('../controllers/uoctinhtonthat.js');
const quanly_xoa_taikhoan = require('../controllers/quanly_xoa_taikhoan.js');
const quanly_mapcto_modem_dcu = require('../controllers/quanly_mapcto_modem_dcu.js');
const quanly_mapcto_doc_ds_cto = require('../controllers/quanly_mapcto_doc_ds_cto.js');
const thongkedangnhap = require('../controllers/thongkedangnhap.js');
const quanly_ds_imei_mapcto = require('../controllers/quanly_ds_imei_mapcto.js');

const quanly_get_thietbi = require('../controllers/quanly_get_thietbi.js');
const quanly_suathietbi = require('../controllers/quanly_suathietbi.js');
const thongtincanhbao_laycanhbaoami = require('../controllers/thongtincanhbao_laycanhbaoami.js');
const thongtincanhbao_laysukien_tucthoi_chitiet = require('../controllers/thongtincanhbao_laysukien_tucthoi_chitiet.js');
const thongtincanhbao_laycanhbaovanhanh_chitiet = require('../controllers/thongtincanhbao_laycanhbaovanhanh_chitiet.js');
const canhbao_matdien = require('../controllers/canhbao_matdien.js');
const thongkechatluong = require('../controllers/thongkechatluong.js');
const thietbi_get_thietbi_by_idthietbi = require('../controllers/thietbi_get_thietbi_by_idthietbi.js');
const thongkechatluong_getdiemdoloi = require('../controllers/thongkechatluong_getdiemdoloi.js');
const scada_thongkesolieu_getIOA = require('../controllers/scada_thongkesolieu_getIOA.js');
const scada_thongkesolieu_laydulieu = require('../controllers/scada_thongkesolieu_laydulieu.js');
const khaithacdulieu_ungtruocsanluong_naptien = require('../controllers/khaithacdulieu_ungtruocsanluong_naptien.js');
const khaithacdulieu_ungtruocsanluong_docketquanap = require('../controllers/khaithacdulieu_ungtruocsanluong_docketquanap.js');
const dienapthap = require('../controllers/dienapthapcontroller.js');
const canhbaodienapthap = require('../controllers/canhbao_dienapthapcontroller.js');
const imeidienapthap = require('../controllers/dienapthap_ds_imei.js');
const dienapthap_ds_imei_cauhinh = require('../controllers/dienapthap_ds_imei_cauhinh.js');
const dienapthap_cauhinh_docthongso = require('../controllers/dienapthap_cauhinh_docthongso.js');
const dienapthap_cauhinh_dieukhien = require('../controllers/dienapthap_cauhinh_dieukhien.js');
const khaithacdulieu_dieukhiendongcat_din_tcp = require('../controllers/khaithacdulieu_dieukhiendongcat_din_tcp.js');

const khaithacdulieu_ungtruocsanluong_token = require('../controllers/khaithacdulieu_ungtruocsanluong_token.js');
const khaithacdulieu_ungtruocsanluong_naptien_token = require('../controllers/khaithacdulieu_ungtruocsanluong_naptien_token.js');
const khaithacdulieu_ungtruocsanluong_docketquanaptoken = require('../controllers/khaithacdulieu_ungtruocsanluong_docketquanaptoken.js');
const lay_tsvh_din = require('../controllers/lay_tsvh_din.js');
const dieukhien_solar = require('../controllers/dieukhien_solar.js');
const khaithacdulieu_dieukhiendongcat_doctrangthai = require('../controllers/khaithacdulieu_dieukhiendongcat_doctrangthai');
const getTSVHScada = require('../controllers/scada_laydulieu');
const doctucthoi = require('../controllers/doctucthoi');
const doctucthoi_tcp = require('../controllers/doctucthoi_tcp');
const getCanhBaoTucThoi = require('../controllers/canhbaosukientucthoi');
const cauhinhcanhbaosukiencongto = require('../controllers/cauhinhcanhbaosukiencongto.js');
const sodomotsoi = require('../controllers/sodomotsoi.js');
const qltk_new = require('../controllers/quanly_taikhoan_doimatkhau.js');
const dongbocmiss = require('../controllers/dongbocmiss.js');
const baocao_vanhanh_ngay = require('../controllers/baocao_vanhanh_ngay.js');
const baocao_ai_vanhanh_ngay = require('../controllers/baocao_ai_vanhanh_ngay.js');
const power_ai = require('../controllers/power_ai.js');
const ai_chat = require('../controllers/ai_chat.js');
const hesWsTicket = require('../controllers/hes-ws-ticket.js');

router.post(
    '/baocao_vanhanh_ngay/:id?',
    baocao_vanhanh_ngay.post
);
router.post('/baocao_ai_vanhanh_ngay/:id?', baocao_ai_vanhanh_ngay.post);
router.get('/ai/health', ai_chat.health);
router.get('/ai/models', ai_chat.models);
router.get('/ai/tools', ai_chat.tools);
router.post('/ai/chat', ai_chat.chat);
router.post('/ai/chat/stream', ai_chat.chatStream);
router.post('/ai/reset', ai_chat.reset);
router.post('/power-ai/analyze/hybrid', power_ai.analyzeHybrid);
router.post('/power-ai/history/bootstrap', power_ai.bootstrapHistory);
router.get('/power-ai/devices/:meterId/health', power_ai.deviceHealth);
router.get('/power-ai/devices/:meterId/forecast', power_ai.deviceForecast);
router.get('/power-ai/alerts', power_ai.alerts);
router.post('/power-ai/chat/device', power_ai.deviceChat);
router.get('/power-ai/status', power_ai.systemStatus);
router.get('/power-ai/model/drift', power_ai.modelDrift);
router.get('/power-ai/p1/feedback/readiness', power_ai.feedbackReadiness);
router.get('/power-ai/p1/incidents', power_ai.p1Incidents);
router.post('/power-ai/p1/incidents', power_ai.p1CreateIncident);
router.patch('/power-ai/p1/incidents/:incidentId', power_ai.p1UpdateIncident);
router.post('/power-ai/p1/alert-feedback', power_ai.p1AlertFeedback);
router.post('/power-ai/p1/alert-feedback/bulk', power_ai.p1AlertFeedbackBulk);
router.get('/power-ai/p1/evaluation/metrics', power_ai.p1EvaluationMetrics);
router.get('/power-ai/p1/evaluation/temporal', power_ai.p1TemporalEvaluation);
router.post('/login/:id?', login.post);
router.post('/hes/ws-ticket', hesWsTicket.post);
router.post('/phanquyen_checkquyen/:id?', phanquyen_checkquyen.post);
router.post('/phanquyen_ganquyen/:id?', phanquyen_ganquyen.post);
router.post('/phanquyen_layds/:id?', phanquyen_layds.post);
router.post('/xoa_thietbi_IEC_104/:id?', xoa_thietbi_IEC_104.post);
router.post('/xoa_cambien_IEC_104/:id?', xoa_cambien_IEC_104.post);
router.post('/xoa_IOA_IEC_104/:id?', xoa_IOA_IEC_104.post);
router.post('/sua_thietbi_IEC_104/:id?', sua_thietbi_IEC_104.post);
router.post('/sua_cambien_IEC_104/:id?', sua_cambien_IEC_104.post);
router.post('/sua_IOA_IEC_104/:id?', sua_IOA_IEC_104.post);
router.post('/ds_quanly_ioa_capnhatloai/:id?', ds_quanly_ioa_capnhatloai.post);
router.post('/khaibaotb_IEC_104/:id?', khaibaotb_IEC_104.post);
router.post('/khaibao_cambien_IEC_104/:id?', khaibao_cambien_IEC_104.post);
router.post('/khaibao_IOA_IEC_104/:id?', khaibao_IOA_IEC_104.post);
router.post('/ds_thietbi_IEC_104/:id?', ds_thietbi_IEC_104.post);
router.post('/ds_thietbi_cambien_IEC_104/:id?', ds_thietbi_cambien_IEC_104.post);
router.post('/khaibao_cambien_IEC_104/:id?', khaibao_cambien_IEC_104.post);
router.post('/ds_ioa_idcambien_IEC_104/:id?', ds_ioa_idcambien_IEC_104.post);
router.post('/ds_danhmuc/:id?', ds_danhmuc.post);
router.post('/quanly_ds_danhmuc/:id?', quanly_ds_danhmuc.post);
router.post('/quanly_ds_khachhang/:id?', quanly_ds_khachhang.post);
router.post('/quanly_ds_chungloaicongto/:id?', quanly_ds_chungloaicongto.post);
router.post('/quanly_themdanhmuc/:id?', quanly_themdanhmuc.post);
router.post('/quanly_them_diemdo/:id?', quanly_them_diemdo.post);
router.post('/quanly_sua_tt_diemdo/:id?', quanly_sua_tt_diemdo.post);
router.post('/quanly_sua_tt_cto/:id?', quanly_sua_tt_cto.post);
router.post('/quanly_thay_imei/:id?', quanly_thay_imei.post);
router.post('/quanly_thaymodem_imei/:id?', quanly_thay_imei.thayModemImei);
router.post('/quanly_suadanhmuc/:id?', quanly_suadanhmuc.post);
router.post('/quanly_xoadanhmuc/:id?', quanly_xoadanhmuc.post);
router.post('/quanly_ds_taikhoan/:id?', quanly_ds_taikhoan.post);
router.post('/quanly_ds_tk_by_danhmucid/:id?', quanly_ds_tk_by_danhmucid.post);
router.post('/quanly_them_taikhoan/:id?', quanly_them_taikhoan.post);
router.post('/quanly_sua_taikhoan/:id?', quanly_sua_taikhoan.post);
router.post('/quanly_ds_diemdo/:id?', quanly_ds_diemdo.post);
router.post('/quanly_lay_tt_diemdo/:id?', quanly_lay_tt_diemdo.post);
router.post('/quanly_ds_congto_byimei/:id?', quanly_ds_congto_byimei.post);
router.post('/quanly_diemdo_thay_cto/:id?', quanly_diemdo_thay_cto.post);
router.post('/quanly_thanhly_diemdo/:id?', quanly_thanhly_diemdo.post);
router.post('/ds_thietbi_quanly_ioa/:id?', ds_thietbi_quanly_ioa.post);
router.post('/khaithacdulieu_laychisocongto/:id?', khaithacdulieu_laychisocongto.post);
router.post('/khaithacdulieu_laythongsovanhanh/:id?', khaithacdulieu_laythongsovanhanh.post);
router.post('/khaithacdulieu_laybieudophutai/:id?', khaithacdulieu_laybieudophutai.post);
router.post('/khaithacdulieu_laychiso_pmax/:id?', khaithacdulieu_laychiso_pmax.post);
router.post('/khaithacdulieu_laydulieusonghai/:id?', khaithacdulieu_laydulieusonghai.post);
router.post('/khaithacdulieu_laychisocongto_dscongto/:id?', khaithacdulieu_laychisocongto_dscongto.post);
router.post('/khaithacdulieu_laychisocongto_chitiet/:id?', khaithacdulieu_laychisocongto_chitiet.post);
router.post('/khaithacdulieu_laythongsovanhanh_chitiet/:id?', khaithacdulieu_laythongsovanhanh_chitiet.post);
router.get('/khaithacdulieu_sukiencongto_layloaicanhbao/:id?', khaithacdulieu_sukiencongto_layloaicanhbao.get);
router.post('/khaithacdulieu_sukiencongto_laysukienct/:id?', khaithacdulieu_sukiencongto_laysukienct.post);
router.post('/khaithacdulieu_laybieudophutai_chitiet/:id?', khaithacdulieu_laybieudophutai_chitiet.post);
router.post('/khaithacdulieu_laychisopmax_chitiet/:id?', khaithacdulieu_laychisopmax_chitiet.post);
router.post('/khaithacdulieu_dieukhiendongcat_laykh/:id?', khaithacdulieu_dieukhiendongcat_laykh.post);
router.post('/khaithacdulieu_dieukhiendongcat_tcp/:id?', khaithacdulieu_dieukhiendongcat_tcp.post);
router.get('/baocaohoatdong_getcambien/:id?', baocaohoatdong_getcambien.get);
router.post('/baocaohoatdong/:id?', baocaohoatdong.post);
router.post('/khaithacdulieu_dieukhiendongcat_insert_lichsu_dongcat/:id?', khaithacdulieu_dieukhiendongcat_insert_lichsu_dongcat.post);
router.post('/scada_thongsovanhanh/:id?', scada_thongsovanhanh.post);
router.post('/scada_thongsovanhanh_getAll/:id?', scada_thongsovanhanh_getAll.post);
router.post('/scada_ai_lotong', scada_ai_lotong.post);
router.post('/scada_canhbao_ds_canhbao/:id?', scada_canhbao_ds_canhbao.post);
router.post('/khaithacdulieu_sukiencongto_laysukien_tucthoi/:id?', khaithacdulieu_sukiencongto_laysukien_tucthoi.post);
router.get('/canhbao_ds_laycanhbaovh/:id?', canhbao_ds_laycanhbaovh.get);
router.post('/canhbao_ds_canhbaovanhanh/:id?', canhbao_ds_canhbaovanhanh.post);
router.post('/canhbao_cauhinh_save_canhbao/:id?', canhbao_cauhinh_save_canhbao.post);
router.post('/cauhinh_canhbao_IEC_104/:id?', cauhinh_canhbao_IEC_104.post);
router.post('/canhbao_cauhinh_save_canhbaovanhanh/:id?', canhbao_cauhinh_save_canhbaovanhanh.post);
router.post('/canhbao_laydanhsach_vanhanh/:id?', canhbao_laydanhsach_vanhanh.post);
router.post('/canhbao_get_udm/:id?', canhbao_get_udm.post);
router.post('/canhbao_save_udm/:id?', canhbao_save_udm.post);
router.post('/canhbao_apdung_udm/:id?', canhbao_apdung_udm.post);
router.post('/canhbao_get_idm/:id?', canhbao_get_idm.post);
router.post('/canhbao_save_idm/:id?', canhbao_save_idm.post);
router.post('/canhbao_apdung_idm/:id?', canhbao_apdung_idm.post);
router.post('/khaibaokhachhang_uploadfile/:id?', khaibaokhachhang_uploadfile.post);
router.post('/thuydien_insertdata/:id?', thuydien_insertdata.post);
router.post('/khaibaokhachhang_kiemtra/:id?', khaibaokhachhang_kiemtra.post);
router.post('/khaibaokhachhang_thuchien/:id?', khaibaokhachhang_thuchien.post);
router.get('/quanly_ds_danhmuc_getthietbi/:id?', quanly_ds_danhmuc_getthietbi.get);
router.post('/quanly_ds_danhmuc_themthietbi/:id?', quanly_ds_danhmuc_themthietbi.post);
router.post('/quanly_ds_danhmuc_suathietbi/:id?', quanly_ds_danhmuc_suathietbi.post);
router.post('/quanly_xoadanhmuc_thietbi/:id?', quanly_xoadanhmuc_thietbi.post); //
router.post('/quanly_ds_danhmuc_user/:id?', quanly_ds_danhmuc_user.post);
router.post('/baocaoloduongday/:id?', baocaoloduongday.post);
router.post('/thietbitruyenthong_getkhachhang/:id?', thietbitruyenthong_getkhachhang.post);
router.post('/thietbitruyenthong_cauhinhdieukhien/:id?', thietbitruyenthong_cauhinhdieukhien.post);
router.post('/thietbitruyenthong_guilenhdoccauhinh/:id?', thietbitruyenthong_guilenhdoccauhinh.post);
router.post('/baocaothongkemangtai/:id?', baocaothongkemangtai.post);
router.post('/uoctinhtonthat/:id?', uoctinhtonthat.post);

router.post('/quanly_xoa_taikhoan/:id?', quanly_xoa_taikhoan.post);
router.post('/quanly_mapcto_modem_dcu/:id?', quanly_mapcto_modem_dcu.post);
router.post('/quanly_mapcto_doc_ds_cto/:id?', quanly_mapcto_doc_ds_cto.post);
router.post('/thongkedangnhap/:id?', thongkedangnhap.post);
router.post('/chitietthongkedangnhap/:id?', thongkedangnhap.getthongkechitiet);
router.post('/quanly_ds_imei_mapcto/:id?', quanly_ds_imei_mapcto.post);
router.post('/quanly_get_thietbi/:id?', quanly_get_thietbi.post);
router.post('/quanly_suathietbi/:id?', quanly_suathietbi.post);
router.post('/thongtincanhbao_laycanhbaoami/:id?', thongtincanhbao_laycanhbaoami.post);
router.post('/thongtincanhbao_laysukien_tucthoi_chitiet/:id?', thongtincanhbao_laysukien_tucthoi_chitiet.post);
router.post('/thongtincanhbao_laycanhbaovanhanh_chitiet/:id?', thongtincanhbao_laycanhbaovanhanh_chitiet.post);
router.post('/canhbao_matdien/:id?', canhbao_matdien.post);
router.post('/thongkechatluong/:id?', thongkechatluong.post);
router.post('/thietbi_get_thietbi_by_idthietbi/:id?', thietbi_get_thietbi_by_idthietbi.post);
router.post('/thongkechatluong_getdiemdoloi/:id?', thongkechatluong_getdiemdoloi.post);
router.post('/scada_thongkesolieu_getIOA/:id?', scada_thongkesolieu_getIOA.post);
router.post('/scada_thongkesolieu_laydulieu/:id?', scada_thongkesolieu_laydulieu.post);
router.post('/khaithacdulieu_ungtruocsanluong_naptien/:id?', khaithacdulieu_ungtruocsanluong_naptien.post);
router.post('/khaithacdulieu_ungtruocsanluong_docketquanap/:id?', khaithacdulieu_ungtruocsanluong_docketquanap.post);
router.post('/dienapthap/:id?', dienapthap.post);
router.post('/canhbaodienapthap/:id?', canhbaodienapthap.post);
router.post('/imeidienapthap/:id?', imeidienapthap.post);
router.post('/dienapthap_ds_imei_cauhinh/:id?', dienapthap_ds_imei_cauhinh.post);
router.post('/dienapthap_cauhinh_docthongso/:id?', dienapthap_cauhinh_docthongso.post);
router.post('/dienapthap_cauhinh_dieukhien/:id?', dienapthap_cauhinh_dieukhien.post);
router.post('/khaithacdulieu_dieukhiendongcat_din_tcp/:id?', khaithacdulieu_dieukhiendongcat_din_tcp.post);
router.post('/khaithacdulieu_ungtruocsanluong_token/:id?', khaithacdulieu_ungtruocsanluong_token.getData);
router.post('/khaithacdulieu_ungtruocsanluong_naptien_token/:id?', khaithacdulieu_ungtruocsanluong_naptien_token.post);
router.post('/khaithacdulieu_ungtruocsanluong_docketquanaptoken/:id?', khaithacdulieu_ungtruocsanluong_docketquanaptoken.post);
router.post('/lay_tsvh_din/:id?', lay_tsvh_din.post);
router.post('/dieukhien_solar/:id?', dieukhien_solar.post);
router.post('/khaithacdulieu_dieukhiendongcat_doctrangthai/:id?', khaithacdulieu_dieukhiendongcat_doctrangthai.post);
router.post('/giamsat/get-tsvh-scada', getTSVHScada.TSVHSCADA);
router.get('/giamsat/get-ds-ioa', getTSVHScada.GETDSIOA);
router.post('/giamsat/save-thietbi-cambien-ioa', getTSVHScada.saveIOA);
router.get('/giamsat/get-danhmuc-tree', getTSVHScada.danhMucTree);
router.post('/giamsat/chitiet-cambien', getTSVHScada.ChitietCambien);
router.get("/giamsat/export-chitiet-cambien-excel", getTSVHScada.exportChiTietCambienExcel);
router.get("/giamsat/get-ds-thietbi-cambien", getTSVHScada.getDsThietbiCambien);
router.post("/giamsat/get-ioa-by-thietbi", getTSVHScada.getIOAByThietBi);
router.post('/giamsat/update-thietbi', getTSVHScada.updateIOA);
router.post('/giamsat/delete-thietbi', getTSVHScada.deleteIOA);
router.post('/giamsat/get-data-thietbi-cambien', getTSVHScada.getDataThietBiCamBien);
router.post('/giamsat/get-thietbi-theo-code', getTSVHScada.getThietBiTheoCode);
router.post("/doctucthoi/getdskh", doctucthoi.DSKHDocTucThoi);
router.post('/doctucthoi/doctucthoi_tcp', doctucthoi_tcp.post);
router.get('/canhbao/sukien', getCanhBaoTucThoi.getCanhBao);
router.post('/cauhinhcanhbaosukiencongto', cauhinhcanhbaosukiencongto.post);
router.post('/read-obis', cauhinhcanhbaosukiencongto.readObis);
router.post('/sodomotsoi/getData', sodomotsoi.post);
router.post('/sodomotsoi/laysukiencanhbao', sodomotsoi.getCanhBao);
router.post('/sodomotsoi/dulieusonghai_ioa', sodomotsoi.getdulieusonghai);
router.post('/quanly_doimatkhau_taikhoan', qltk_new.doimatkhau_tk);

router.post('/dongbocmiss_uploadfile', dongbocmiss.post);
router.post('/dongbocmiss_napdulieu', dongbocmiss.napdulieu);
const zdashboard_ = require('../controllers/zdashboard_controller.js');
router.post('/get_child_codes', zdashboard_.get_child_codes);
router.post("/get_meter_by_child_code", zdashboard_.get_meter_by_child_code);
const qlnhamay = require('../controllers/quanly_nhamay.js');
router.post('/quanly_ds_nhamay/:id?', qlnhamay.quanly_ds_nhamay);
router.post('/quanly_lay_tt_nhamay/:id?', qlnhamay.quanly_lay_tt_nhamay);
router.post('/quanly_them_nhamay/:id?', qlnhamay.quanly_them_nhamay);
router.post('/quanly_sua_nhamay/:id?', qlnhamay.quanly_sua_nhamay);
router.post('/quanly_xoa_nhamay/:id?', qlnhamay.quanly_xoa_nhamay);
const qltaikhoan = require('../controllers/quanly_taikhoan_controller.js');
router.post('/ds_taikhoan', qltaikhoan.getDanhSach);
router.post('/taikhoan/them', qltaikhoan.them);
router.post('/taikhoan/sua', qltaikhoan.sua);
router.post('/taikhoan/xoa', qltaikhoan.xoa);
router.post('/taikhoan/doimatkhau', qltaikhoan.doiMatKhau);
module.exports = router;
